{% set name = "pymdown-extensions" %}
{% set version = "10.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymdown_extensions-{{ version }}.tar.gz
  sha256: aace82bcccba3efc03e25d584e6a22d27a8e17caa3f4dd9f207e49b787aa9a91

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling >=0.21.1
  run:
    - markdown >=3.6
    - pyyaml
    - python
  run_constrained:
    - Pygments >=2.19.1

test:
  ## TODO re-enable pytest when pygments >=2.12 is available.
  # source_files:
  #   - tests
  requires:
    - pip
  #   - pytest
  #   - pygments >=2.12
  imports:
    - pymdownx
  commands:
    - pip check
    # - pytest

about:
  home: https://github.com/facelessuser/pymdown-extensions
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Extension pack for Python Markdown.
  description: |
    PyMdown Extensions is a collection of extensions for Python Markdown.
    They were originally written to make writing documentation more enjoyable.
    They cover a wide range of solutions, and while not every extension
    is needed by all people, there is usually at least one useful extension for everybody.
  doc_url: https://facelessuser.github.io/pymdown-extensions/
  dev_url: https://github.com/facelessuser/pymdown-extensions

extra:
  recipe-maintainers:
    - dhirschfeld
    - monaldoj
    - ewels
    - maxibor
