travis:
  secure:
    BINSTAR_TOKEN: JJ0DloRNdKfFiyxQJSyduyxfsLIKoFBLrtGJQxJBSfK3QLM/3yMp/9qd5uY3kyWOKh8QpI4vVLOlugkd/mZ+I+1ot3+ESsUY4CQo/9oiINMDUpE0wcX1MMAx8ykU+lKD5tS4LoXaoBbMzmocmvk3qXaaxVYgh6FqgEUM4YCPOmvMtSSI0luNaeJdXgxo3OdxluSVsWDgvW/OmACx6OBGDXldSLApt15klJCju5m1S9kHAO5uRgwUW8w20fTF1BTAVLr0Lixa0VHKDTNo1lU4MQMihfebXkgMpOJH1oiZUT5SpAbWh44xsMSqj3q+F0dpPfju6aRDFqEX2vjG9RqF2zS70vJyWXnryCfJXCOF676UJXDMEXFwRlr80OS35y/AzNytBHYkJO/U5dGwrU6e/njd3NLKBwy+yrEYfH08Jlf57vBfV9h0+nyPETUyykjW9rqfhJAj8TGeWUzYt2hH4mOlT77QjG4coV9J7nEX+pkwenPHB/CE+9HlY5GaYjp/GwH5H0pXnnV+337xUBfLAoPw7uh7/4iPTgWMAfi7gUlmqWIL6UxEppMGp55JJG8eTeG2H5wxnp0C9FK+hF6JxGeWf+KeKSTHaT+x4TXC0eJYuKVQM5MmReUsFTjGl0d8ogjmCPV4shiOclZmVrysFLfvnC6E2/4cow7f3dgAu6U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
